/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.italbytz.infrastructure.openmensa

import kotlin.test.Test
import kotlin.test.assertFalse

class LibraryTest {
    @Test fun getCanteens() {
        val classUnderTest = OpenMensaService()
        val result = classUnderTest.getCanteens().execute().body()!!
        assertFalse(result.isEmpty())
    }

    @Test fun getDays() {
        val classUnderTest = OpenMensaService()
        val result = classUnderTest.getDays(1).execute().body()!!
        assertFalse(result.isEmpty())
    }

    @Test fun getTodaysMeals() {
        val classUnderTest = OpenMensaService()
        try {
            val result = classUnderTest.getTodaysMeals(1).execute().body()!!
            assertFalse(result.isEmpty())
        } catch (e: NoMealsForDateException) {

        } catch (e: MensaClosedException) {

        }
    }
}
