/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.italbytz.infrastructure.openmensa

import kotlin.test.Test
import kotlin.test.assertFalse

class LibraryTest {
    @Test fun getCanteens() {
        val classUnderTest = OpenMensaService()
        val result = classUnderTest.getCanteens().execute().body()!!
        assertFalse(result.isEmpty())
    }
}
